steps:

  - id: 'tf-init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    dir: 'gke-cluster-demo'
    args:
      - '-c'
      - |
        terraform init

  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    dir: 'gke-cluster-demo'
    args:
      - '-c'
      - |
        terraform plan -out=tfplan -var-file=terraform.tfvars

  - id: 'tf-apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    dir: 'gke-cluster-demo'
    args:
      - '-c'
      - |
        terraform apply -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY
