steps:

  - id: 'tf-init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    dir: 'gke-cluster-demo'
    args:
      - '-c'
      - |
        terraform init

  - id: 'tf-refresh'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    dir: 'gke-cluster-demo'
    args:
      - '-c'
      - |
        terraform refresh -var-file=terraform.tfvars

  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    dir: 'gke-cluster-demo'
    args:
      - '-c'
      - |
        terraform plan -var-file=terraform.tfvars

  - id: 'tf-apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    dir: 'gke-cluster-demo'
    args:
      - '-c'
      - |
        terraform apply -auto-approve

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
